# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IoTVodafoneTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'IoTVodafoneTaskTests' do
    inherit! :search_paths

  end
  # Pods for IoTVodafoneTask

    pod 'Alamofire'
    pod 'SVProgressHUD'
    pod 'SDWebImage', '~> 5.0'
end
